# Generated by Django 5.2.5 on 2025-08-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdays', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdaymodel',
            name='gift_idea',
            field=models.TextField(blank=True, max_length=120, null=True),
        ),
    ]
